* Multigrid demo in 1D

This demo shows how iterative Jacobi, Gauss-Seidel and Multigrid
solutions converge in case of Poisson equation in 1D for a simple,
fixed source. The iteration is stopped when the change in the residual
between subsequent iterations is small.

The output of the demo can be directly piped to gnuplot. Also, the
demo uses gnuplot to visualize the development of solution at runtime.

** Requirements

On Ubuntu 15.10, in addition to what one gets by default, I have installed
the following packages:

- synaptic
- emacs
- git
- gfortran
- makedepf90
- gnuplot5

** Build

#+BEGIN_SRC bash
cd build
make -f ../src/makefile
#+END_SRC

** Play

#+BEGIN_SRC bash
time ./poisson_identity_test_1d 20 DD | tee >(gnuplot --persist)
#+END_SRC

One can vary the size of the system and the boundary conditions and
the solver with the 1st and 2nd command line argument,
respectively. Valid values for boundary conditions are ~DD~, ~NN~ and
~PP~, for Dirichlet, Neumann, and periodic boundary conditions,
respectively.
